name: s3-data-pipeline-workflow

on:
  push

env:
  BUCKET_NAME: 'environmental-stock-data-bucket'
  AWS_REGION: 'us-east-2'

permissions:
  id-token: write
  contents: read

jobs:
  run-s3-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::823222780510:role/GithubS3Access
          role-session-name: s3FileUpload
          aws-region: ${{ env.AWS_REGION }}

      - name: run s3 data pipeline
        run: python s3_data_pipeline.py

      - name: Check for changes # create env variable indicating if any changes were made
        id: git-check
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push if changes
        if: env.changes == 'true' # if changes made push new data to repo
        run: |
          git commit -m "uploaded data to s3"
          git push
