name: sync-github-data-to-s3

on:
  workflow_dispatch:

env:
  BUCKET_NAME: 'environmental-stock-data-bucket'
  AWS_REGION: 'us-east-2'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: audreydottech/esg-data-pipeline@main
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './data/**'
          role-session-name: s3FileUpload
          aws-region: ${{ env.AWS_REGION }}

